# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R

sudo: required

cache: packages

r:
  - release

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

os:
  - linux

r_packages:
  - covr
  - devtools
  - knitr
  - roxygen2
  - rmarkdown
  - testthat
  - glue
  - jsonlite
  - ini
  - yaml
  - RcppTOML
  - prettydoc

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - Rscript -e 'library("covr"); covr::codecov()'
