title = "configr help urls configuration file"
[urls]
json_wiki = "https://en.wikipedia.org/wiki/JSON"
yaml_wiki = "https://en.wikipedia.org/wiki/YAML"
ini_wiki = "https://en.wikipedia.org/wiki/INI_file"
toml_wiki = "https://en.wikipedia.org/wiki/TOML"
json_org = "http://json.org/"
yaml_org = "http://yaml.org/"
toml_official_github = "https://github.com/toml-lang/toml"
toml_pypi = "https://pypi.org/project/toml/"
toml_cran = "https://CRAN.R-project.org/package=RcppTOML"
json_stackoverflow_search = "https://stackoverflow.com/search?q=json"
yaml_stackoverflow_search = "https://stackoverflow.com/search?q=yaml"
ini_stackoverflow_search = "https://stackoverflow.com/search?q=ini"
toml_stackoverflow_search = "https://stackoverflow.com/search?q=toml"
json_github_search = "https://github.com/search?q=json"
ini_github_search = "https://github.com/search?q=ini"
yaml_github_search = "https://github.com/search?q=yaml"
toml_github_search = "https://github.com/search?q=toml"
ini_js_github = "https://github.com/npm/ini"
ini_go_github = "https://github.com/go-ini/ini"
yaml_go_github = "https://github.com/go-yaml/yaml"
yaml_js_github = "https://github.com/nodeca/js-yaml"
yaml_python_github = "https://github.com/adrienverge/yamllint"
yaml_r_github = "https://github.com/viking/r-yaml/"
json_r_github = "https://github.com/jeroen/jsonlite/"
json_js_github = "https://github.com/trentm/json"
json_cplus_github = "https://github.com/nlohmann/json"
json_go_github = "https://github.com/tomnomnom/gron"
json_python_github = "https://github.com/Julian/jsonschema"
toml_r_github = "https://github.com/eddelbuettel/rcpptoml"
toml_go_github = "https://github.com/BurntSushi/toml"
toml_python_github = "https://github.com/uiri/toml"
toml_js_github = "https://github.com/BinaryMuse/toml-node"
