config.json <- system.file("extdata", "config.json", package = "configr")
config.yaml <- system.file("extdata", "config.yaml", package = "configr")
config.ini <- system.file("extdata", "config.ini", package = "configr")
config.toml <- system.file("extdata", "config.toml", package = "configr")
config.list <- list(ini = config.ini, json = config.json, toml = config.toml, yaml = config.yaml)

for (i in c("ini", "json", "toml", "yaml")) {
  config <- read.config(config.list[[i]], rcmd.parse = FALSE)
  x <- parse.extra(config, list(debug = "TRUE"))
  expect_that(is.list(x), equals(TRUE))
  expect_that(x$default$debug, equals("TRUE {{debug2}}"))
  other.config <- system.file("extdata", "config.other.yaml", package = "configr")
  x <- parse.extra(config, list(debug = "TRUE", debug2 = "FALSE"), other.config)
  expect_that(is.list(x), equals(TRUE))
  expect_that(x$default$debug, equals("TRUE FALSE"))
  expect_that(x$default$test, equals("/tmp"))
  expect_that(x$comments$test_parse, equals("123 234"))
  x <- parse.extra(config, list(debug = "TRUE", debug2 = "FALSE"), other.config = other.config, 
    rcmd.parse = T)
  expect_that(is.list(x), equals(TRUE))
  expect_that(x$default$debug, equals("TRUE FALSE"))
  expect_that(x$default$test, equals("/tmp"))
  expect_that(x$comments$test_parse, equals("123 234"))
  expect_that(x$comments$test_parse2, equals("1003 234 FALSE"))
  expect_that(x$comments$test_parse4, equals("0034 1003 234 FALSE"))
}
